version: '3'
vars:
  GOOS: "{{default OS .GOOS}}"
  MVN: '{{if eq .GOOS "windows"}}mvnw.cmd{{else}}./mvnw{{end}}'
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'
  DC_DIR: "docker"
  DC_FILE: "{{.DC_DIR}}/compose.yml"

tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [format]
    cmds:
      - "{{.MVN}} verify"

  format:
    cmds:
      - "{{.MVN}} spotless:apply"

  build_image:
    cmds:
      - "{{.MVN}} spring-boot:build-image -DskipTests"
  start:
    deps: [build_image]
    cmds:
      - docker compose -f "{{.DC_FILE}}" up --force-recreate -d

  stop:
    cmds:
      - docker compose -f "{{.DC_FILE}}" stop
      - docker compose -f "{{.DC_FILE}}" rm -f

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"
